# Generated by Django 5.1.5 on 2025-01-22 05:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='R_D',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('room_type', models.CharField(max_length=50)),
                ('room_description', models.CharField(max_length=500)),
                ('space_for_adult', models.IntegerField()),
                ('space_for_child', models.IntegerField()),
                ('price', models.IntegerField()),
            ],
        ),
    ]
