# Generated by Django 5.1.5 on 2025-01-27 04:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_rooms'),
    ]

    operations = [
        migrations.RenameField(
            model_name='rooms',
            old_name='room_aviablity',
            new_name='room_availability',
        ),
        migrations.AlterField(
            model_name='r_d',
            name='room_type',
            field=models.CharField(max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='rooms',
            name='room_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rooms', to='home.r_d', to_field='room_type'),
        ),
        migrations.AlterUniqueTogether(
            name='rooms',
            unique_together={('room_type', 'room_number')},
        ),
    ]
