# Generated by Django 5.1.5 on 2025-02-09 07:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_contact'),
    ]

    operations = [
        migrations.AddField(
            model_name='rooms',
            name='from_date',
            field=models.DateField(default=None),
        ),
        migrations.AddField(
            model_name='rooms',
            name='to_date',
            field=models.DateField(default=None),
        ),
    ]
