# Generated by Django 5.1.5 on 2025-02-09 07:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_rooms_from_date_rooms_to_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rooms',
            name='from_date',
            field=models.DateField(default=None, null=True),
        ),
        migrations.AlterField(
            model_name='rooms',
            name='to_date',
            field=models.DateField(default=None, null=True),
        ),
    ]
