# Generated by Django 5.1.5 on 2025-02-09 07:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0008_alter_rooms_from_date_alter_rooms_to_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rooms',
            name='from_date',
            field=models.DateField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='rooms',
            name='to_date',
            field=models.DateField(blank=True, default=None, null=True),
        ),
    ]
