# Generated by Django 5.1.5 on 2025-02-09 09:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0009_alter_rooms_from_date_alter_rooms_to_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='temp',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=255)),
                ('rooms', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.r_d', to_field='room_type')),
            ],
        ),
        migrations.CreateModel(
            name='User_Booked_Room_Details',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(blank=True, max_length=12, null=True)),
                ('room_number', models.CharField(max_length=50)),
                ('number_of_rooms', models.IntegerField()),
                ('adults', models.IntegerField()),
                ('child', models.IntegerField(blank=True, default=0, null=True)),
                ('check_in', models.DateField()),
                ('check_out', models.DateField()),
                ('total_amount', models.IntegerField()),
                ('room_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.r_d', to_field='room_type')),
            ],
        ),
    ]
