# Generated by Django 5.1.5 on 2025-02-09 09:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0010_temp_user_booked_room_details'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user_booked_room_details',
            name='room_number',
        ),
    ]
