# Generated by Django 5.1.5 on 2025-02-10 08:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0011_remove_user_booked_room_details_room_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user_booked_room_details',
            name='number_of_rooms',
            field=models.CharField(max_length=255),
        ),
    ]
