# Generated by Django 5.1.5 on 2025-02-10 09:28

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0012_alter_user_booked_room_details_number_of_rooms'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rooms',
            name='from_date',
        ),
        migrations.RemoveField(
            model_name='rooms',
            name='to_date',
        ),
        migrations.RemoveField(
            model_name='user_booked_room_details',
            name='number_of_rooms',
        ),
        migrations.AddField(
            model_name='user_booked_room_details',
            name='Booked_on_date',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='user_booked_room_details',
            name='room_allocated',
            field=models.JSONField(default=list),
        ),
        migrations.AlterField(
            model_name='user_booked_room_details',
            name='room_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='booked_rooms', to='home.r_d', to_field='room_type'),
        ),
    ]
